export const SIZE = 9;
export const WHITE_TERRITORY_BONUS = 0;
export const SPECIALS = new Set(["general", "diplomat", "wizard"]);
export const DEPLOY_ORDER = ["soldier", "general", "diplomat", "wizard", "king"];
export const AI_PROFILES = ["balanced", "aggressive", "defensive"];
export const PVE_HUMAN = "blue";
export const PVE_AI = "red";

export const TEXT = {
  en: {
    appTitle: "Daeguk: Ascension", brandMain: "DAEGUK", brandSubtitle: "ASCENSION", splashEyebrow: "Daeguk", splashLoading: "Checking game server…", splashReady: "Entering lobby…", splashOffline: "Online server unavailable. Entering lobby…", splashImagePlaceholder: "Opening image",
    deploy: "Deploy", language: "Language", chooseMode: "Select Match", chooseModeDescription: "9×9 territory battle with Black playing 1st and White 2nd.",
    tutorial: "Tutorial", tutorialDescription: "Step-by-step training for Black (1st) & White (2nd) rules, King, and skills.", puzzle: "Challenge", puzzleDescription: "Solve tactical puzzles to raise your rank.", challengeRanks: "Challenge Ranks", challengeRanksDescription: "Clear each rank to unlock the next challenge.", challengeComplete: "Challenge Complete", challengeIncomplete: "Challenge Incomplete", nextChallenge: "Next Challenge", retryChallenge: "Retry", backToChallenges: "Back to Challenges", rankLocked: "Locked", rankComplete: "Complete", rankReady: "Ready", comingSoon: "Coming Soon", modeLocked: "Complete the first Challenge rank", exitTutorial: "Exit", nextTutorial: "Next",
    tutorialStep: "Step {current} / {total}", tutorialKing: "Black plays first and White plays second. Deploy your King first.", tutorialKingPlaced: "For the next 4 turns (5 turns for special units), your opponent cannot enter the King's sanctuary.",
    tutorialWallDefense: "What happens when your unit connects to a fortress wall? Place a Black Soldier to surround the White Soldier.",
    tutorialWallDefensePlaced: "The White Soldier was not captured because it is connected to its own fortress wall.",
    tutorialWallCapture: "The fortress wall also helps surround enemies. Place a White Soldier to capture the Black Soldier.",
    tutorialWallCapturePlaced: "The Black Soldier was captured, surrounded by White walls and soldiers.",
    tutorialCapture: "How can you capture the Black Soldier?",
    tutorialGeneral: "Place the General in the center and see how its ability triggers when surrounded.",
    tutorialDiplomat: "Place the Diplomat in the center and see how its ability triggers when surrounded.",
    tutorialWizard: "Place the Wizard in the center and see how its ability and teleportation work.",
    tutorialWizardTeleport: "The Wizard ability triggered. Teleport to any empty square.",
    tutorialGeneralPlaced: "The General ability triggered. When surrounded, the General eliminates adjacent enemies and becomes a standard Soldier.",
    tutorialDiplomatPlaced: "The Diplomat ability triggered. When surrounded, the Diplomat converts adjacent enemies to your side and becomes a standard Soldier.",
    tutorialWizardPlaced: "Teleport complete. The Wizard becomes a standard Soldier.",
    tutorialGeneralReady: "General deployed. Click Next.",
    tutorialDiplomatReady: "Diplomat deployed. Click Next.",
    tutorialWizardReady: "Wizard deployed. Click Next.",
    tutorialBlackPreparing: "Black is preparing the fourth surrounding move…",
    tutorialSurroundComplete: "The surround is complete. The special ability will activate shortly…",
    tutorialCapturePlaced: "The Black Soldier was captured.",
    tutorialComplete: "Tutorial complete. You learned King deployment, wall use, capture, and all three special-unit abilities.",
    pveMode: "AI Match", pveDescription: "Choose a side and play against the AI", pveSidePrompt: "Choose an AI difficulty.", choosePreferredSide: "Choose your preferred side.",
    pveNovice: "Novice", pveIntermediate: "Intermediate", pveAdvanced: "Advanced", pveExpert: "Expert", pveGrandmaster: "Grandmaster",
    pveBeginner: "Novice",
    pveNoviceDescription: "Level 1: Basic tactical maneuvers and special units.",
    pveIntermediateDescription: "Level 2: Strategic positioning and diplomatic pressure.",
    pveAdvancedDescription: "Level 3: Teleportation tricks and unpredictable attacks.",
    pveExpertDescription: "Level 4: Multi-step foresight and coordinated trapping.",
    pveGrandmasterDescription: "Level 5: Unyielding King fortress, 100% checkmate capture, peak performance.",
    pveBeginnerDescription: "Level 1: Basic tactical maneuvers and special units.",
    onlinePvp: "Online PvP", pvpDescription: "Create or join a private network room",
    networkLobby: "Network Lobby", networkPrompt: "Create a board or join an open board.", roomCode: "Room code",
    openRooms: "Open Boards", refreshRooms: "Refresh", noOpenRooms: "No open boards.", boardName: "Board {number}", boardWaiting: "Waiting",
    createBoard: "Create", enterBoard: "Enter",
    chooseSide: "Choose your side", chooseSideAfterJoin: "Both players joined. Choose Black (1st) or White (2nd).", blackSide: "Black (1st)", whiteSide: "White (2nd)",
    enterCode: "Enter code", createRoom: "Create Room", joinRoom: "Join Room", back: "Back", lobby: "Lobby", requestRematch: "Request rematch", acceptRematch: "Accept Rematch", opponentRematchOffered: "Opponent requested a rematch.", rematchOfferedToast: "Opponent requested a rematch!", declineRematch: "Decline", opponentDeclinedRematch: "Opponent declined the rematch. Returned to lobby.", rematchDeclinedSelf: "Rematch declined. Returned to lobby.", opponentLeftRoom: "Opponent has left the room.", specialUnit: "Special Unit",
    rpsPrompt: "The winner of Rock-Paper-Scissors plays Black (1st).", rpsWaitingOpponent: "Choice made! Waiting for opponent…", rpsDraw: "Draw! Choose again.", rpsWin: "You won! Starting as Black (1st).", rpsLose: "You lost! Starting as White (2nd).", scissors: "Scissors", rock: "Rock", paper: "Paper",
    dontShowAgain: "Do not show this unit explanation again", gotIt: "Got It", matchComplete: "Match Complete",
    redTerritory: "Black territory", blueTerritory: "White territory", redCaptures: "Black captures", blueCaptures: "White captures",
    redSkills: "Black skills used", blueSkills: "White skills used", playAgain: "Play Again", wizardMoveButton: "Move", cancelAbility: "Do Not Move",
    undo: "Undo", resign: "Resign", resignConfirmTitle: "Do you want to resign?", cancel: "Cancel", confirm: "Confirm", resignReason: "{side} resigned.", home: "Home", newGame: "New Game", settings: "Settings", close: "Close", downloadPveJournal: "Download PvE record", pveJournalDownloaded: "PvE JSONL record downloaded.", resetSpecialHelp: "Show detailed Challenge guidance", specialHelpReset: "Detailed Challenge guidance will be shown.", specialHelpHidden: "Challenge guidance will be concise.", soundSettings: "Sound", musicSetting: "Music", sfxSetting: "Effects", soundComingSoon: "Coming soon", specialHelpSetting: "Challenge guidance", redUnits: "Black units", blueUnits: "White units",
    soldier: "Soldier", king: "King", general: "General", diplomat: "Diplomat", wizard: "Wizard",
    used: "Used", kingFirst: "King first", left: "{count} left", available: "Available",
    red: "Black", blue: "White", turn: "{side} turn", turnWithTime: "{side} turn {time}s", thinking: " thinking", wins: "{side} wins",
    hiddenUnit: "a hidden unit", notConnected: "The online match is not connected.", createOrJoin: "Create a board or enter an open board.",
    rematchWaiting: "Waiting for opponent…", connecting: "Connecting to game server…",
    disconnected: "Disconnected from game server.", opponentDisconnected: "Opponent disconnected.", serverUnavailable: "Game server is unavailable. Online PvP requires the WebSocket server.",
    invalidServerResponse: "The game server sent an invalid response.",
    roomWaiting: "{room}. Waiting for opponent…", sideSelectionReady: "{room} · Opponent joined. Choose Black or White.", roomPlayer: "{room} · You are {side}.",
    serverRejected: "The game server rejected the request.", enterRoomCode: "Enter a room code.",
    resultWin: "{side} Wins", allEliminated: "All enemy units were eliminated.",
    timeExpired: "Time limit exceeded (30s).",
    resultDraw: "Draw", draw: "Draw", boardFilled: "Board filled: Black {red} - White {blue}.",
    noLegalMoves: "No legal deployments remained: Black {red} - White {blue}.",
    autoPass: "{side} passed the turn.", taunt: "Taunt!", tauntBubble: "Chicken!!",
    passNoticeTitle: "Pass", noLegalMovesPass: "{side} has no legal moves and passes the turn.", confirm: "OK",
    suicideWarningTitle: "Confirm Suicide Move", suicideWarning: "This unit will die immediately if placed here.",
    cancelSuicide: "Reselect", confirmSuicide: "Place Anyway",
    kingTerritoryBlocked: "You cannot deploy inside the opponent King's surrounding territory until that player completes five deployments.",
    kingOverlapBlocked: "The King's sanctuary cannot overlap with the opponent King's sanctuary (must be at least 3 squares apart).",
    kingCaptured: "{side} King was captured.",
    activateSpecialTitle: "{unit} ability ready",
    activateSpecialPrompt: "{side}'s {unit} was surrounded. Activate the ability to resolve the capture reaction.",
    activateSpecialButton: "Activate {unit} Ability",
    waitingSpecialPrompt: "Waiting for {side} to activate a surrounded special unit.",
    puzzleComplete: "Puzzle Complete",
    puzzleFailed: "Puzzle Failed",
    puzzleSolvedReason: "Correct. {title} solved in {moves} move(s).",
    tutorialPuzzleSolvedReason: "Basic training complete. Continue to the next puzzle.",
    puzzleFailedReason: "The move limit was reached. Try the puzzle again.",
    puzzleInvalidReason: "This puzzle data is invalid. Please try another puzzle.",
    puzzleProgress: "{rank} · Puzzle {current} / {total} · {movesLeft} move(s) left",
  },
  ko: {
    appTitle: "고수의 대국", brandMain: "DAEGUK", brandSubtitle: "고수의 대국", splashEyebrow: "대국", splashLoading: "게임 서버 확인 중…", splashReady: "로비로 이동 중…", splashOffline: "온라인 서버를 사용할 수 없습니다. 로비로 이동 중…", splashImagePlaceholder: "대문 이미지",
    deploy: "유닛 배치", language: "언어", chooseMode: "대국 선택", chooseModeDescription: "흑돌 선공, 백돌 후공으로 진행되는 9×9 대국",
    tutorial: "튜토리얼", tutorialDescription: "선공(흑)·후공(백)과 왕 배치, 기본 규칙을 단계별로 연습", puzzle: "챌린지", puzzleDescription: "퍼즐을 풀어 자신의 등급을 올리세요.", challengeRanks: "챌린지", challengeRanksDescription: "각 등급을 완료하면 다음 챌린지가 열립니다.", challengeComplete: "챌린지 완료", challengeIncomplete: "챌린지 미완료", nextChallenge: "다음 챌린지", retryChallenge: "다시 도전", backToChallenges: "챌린지로", rankLocked: "잠김", rankComplete: "완료", rankReady: "도전 가능", comingSoon: "준비 중", modeLocked: "첫 챌린지 등급을 완료하세요", exitTutorial: "종료", nextTutorial: "다음",
    tutorialStep: "{current} / {total} 단계", tutorialKing: "흑돌이 선공, 백돌이 후공으로 대국을 시작합니다. 먼저 왕을 배치하세요.", tutorialKingPlaced: "다음 4번(특수유닛은 5번)의 턴 동안 상대방은 왕의 성역에 접근할 수 없습니다.",
    tutorialWallDefense: "내 유닛이 성벽에 연결되어 있으면 어떻게 될까요? 흑 병사를 놓아 백 병사를 포위해보세요.",
    tutorialWallDefensePlaced: "백 병사는 자신의 성벽에 연결되어 있어 포획되지 않았습니다.",
    tutorialWallCapture: "성벽도 아군 병사처럼 포위에 참여합니다. 백 병사를 놓아 흑 병사를 포획해보세요.",
    tutorialWallCapturePlaced: "흑 병사가 백 성벽과 백 병사들에게 포위되어 포획되었습니다.",
    tutorialCapture: "어떻게 하면 흑 병사를 잡을 수 있을까요?",
    tutorialGeneral: "장군을 가운데에 배치하고 포위될 때 능력이 어떻게 발동하는지 확인하세요.",
    tutorialDiplomat: "외교관을 가운데에 배치하고 포위될 때 능력이 어떻게 발동하는지 확인하세요.",
    tutorialWizard: "마법사를 가운데에 배치하고 포위될 때 능력과 순간이동을 확인하세요.",
    tutorialWizardTeleport: "마법사 스킬이 발동되었습니다. 원하는 빈칸으로 이동할 수 있습니다.",
    tutorialGeneralPlaced: "장군 스킬이 발동되었습니다. 장군은 포위되면 인접한 적을 사살한 뒤 일반 병사로 전환됩니다.",
    tutorialDiplomatPlaced: "외교관 스킬이 발동되었습니다. 외교관은 포위되면 인접한 적을 아군으로 포섭한 뒤 일반 병사로 전환됩니다.",
    tutorialWizardPlaced: "순간이동이 완료되었습니다. 마법사는 일반 병사로 전환됩니다.",
    tutorialGeneralReady: "장군을 배치했습니다. 다음을 누르세요.",
    tutorialDiplomatReady: "외교관을 배치했습니다. 다음을 누르세요.",
    tutorialWizardReady: "마법사를 배치했습니다. 다음을 누르세요.",
    tutorialBlackPreparing: "흑이 마지막 포위 수를 준비하고 있습니다…",
    tutorialSurroundComplete: "포위가 완성되었습니다. 잠시 후 특수 능력이 발동합니다…",
    tutorialCapturePlaced: "흑 병사가 포획되었습니다.",
    tutorialComplete: "튜토리얼 완료! 왕 배치, 성벽 활용, 포획과 세 특수 유닛의 능력을 익혔습니다.",
    pveMode: "AI 대국", pveDescription: "AI 대국", pveSidePrompt: "AI 난이도를 선택하세요", choosePreferredSide: "원하는 진영을 선택하세요",
    pveNovice: "초급", pveIntermediate: "중급", pveAdvanced: "상급", pveExpert: "달인", pveGrandmaster: "신의 한 수",
    pveBeginner: "초급",
    pveNoviceDescription: "1단계: 특수 기물 기본 활용 및 전술 공방",
    pveIntermediateDescription: "2단계: 외교관 및 진형 장악 중심 전략",
    pveAdvancedDescription: "3단계: 마법사 도약 및 기습 침투 전술",
    pveExpertDescription: "4단계: 2~3수를 내다보는 연계 수읽기",
    pveGrandmasterDescription: "5단계: 무결점 왕 방어와 100% 킬각을 포착하는 극강 AI",
    pveBeginnerDescription: "1단계: 특수 기물 기본 활용 및 전술 공방",
    onlinePvp: "온라인 대국", pvpDescription: "비공개 방을 만들거나 참가",
    networkLobby: "온라인 대기실", networkPrompt: "대국장을 만들거나 열린 대국장에 참가하세요.", roomCode: "방 코드",
    openRooms: "열린 대국장", refreshRooms: "새로고침", noOpenRooms: "열린 대국장이 없습니다.", boardName: "제{number}대국장", boardWaiting: "대기 중",
    createBoard: "만들기", enterBoard: "입장",
    chooseSide: "진영 선택", chooseSideAfterJoin: "두 플레이어가 참가했습니다. 흑(선공) 또는 백(후공)을 선택하세요.", blackSide: "흑 (선공)", whiteSide: "백 (후공)",
    enterCode: "코드 입력", createRoom: "방 만들기", joinRoom: "방 참가", back: "뒤로", lobby: "로비", requestRematch: "재대국 요청", acceptRematch: "재대국 수락", opponentRematchOffered: "상대가 재대국을 요청했습니다.", rematchOfferedToast: "상대방이 재대국을 신청했습니다!", declineRematch: "거절", opponentDeclinedRematch: "상대방이 재대국을 거절하여 온라인 대기실로 이동했습니다.", rematchDeclinedSelf: "재대국을 거절하고 온라인 대기실로 이동했습니다.", opponentLeftRoom: "상대방이 대국실을 나갔습니다.", specialUnit: "특수 유닛",
    rpsPrompt: "가위바위보를 이기는 사람이 흑(선공)을 잡습니다.", rpsWaitingOpponent: "선택 완료! 상대의 선택을 기다리는 중…", rpsDraw: "비겼습니다! 다시 선택하세요.", rpsWin: "가위바위보 승리! 흑(선공)으로 시작합니다.", rpsLose: "가위바위보 패배! 백(후공)으로 시작합니다.", scissors: "가위", rock: "바위", paper: "보",
    dontShowAgain: "이 유닛 설명을 다시 표시하지 않기", gotIt: "확인", matchComplete: "대국 종료",
    redTerritory: "흑 영역", blueTerritory: "백 영역", redCaptures: "흑 포획", blueCaptures: "백 포획",
    redSkills: "흑 스킬 사용", blueSkills: "백 스킬 사용", playAgain: "다시 대국", wizardMoveButton: "이동", cancelAbility: "이동 안함",
    undo: "한수 물리기", resign: "기권", resignConfirmTitle: "기권하시겠습니까?", cancel: "취소", confirm: "확인", resignReason: "{side} 기권패", home: "홈", newGame: "새 게임", settings: "설정", close: "닫기", downloadPveJournal: "PvE 대국 기록 내려받기", pveJournalDownloaded: "PvE JSONL 대국 기록을 내려받았습니다.", resetSpecialHelp: "상세한 챌린지 도움말 표시", specialHelpReset: "상세한 챌린지 도움말을 표시합니다.", specialHelpHidden: "챌린지 도움말을 간결하게 표시합니다.", soundSettings: "사운드", musicSetting: "배경음악", sfxSetting: "효과음", soundComingSoon: "준비 중", specialHelpSetting: "챌린지 도움말", redUnits: "흑 유닛", blueUnits: "백 유닛",
    soldier: "병사", king: "왕", general: "장군", diplomat: "외교관", wizard: "마법사",
    used: "사용 완료", kingFirst: "왕 먼저", left: "{count}개", available: "사용 가능",
    red: "흑", blue: "백", turn: "{side} 턴", turnWithTime: "{side} 턴 {time}s", thinking: " 생각 중", wins: "{side} 승리",
    hiddenUnit: "숨겨진 유닛", notConnected: "온라인 경기에 연결되지 않았습니다.", createOrJoin: "대국장을 만들거나 입장하세요.",
    rematchWaiting: "재대국 요청됨 (대기 중…)", connecting: "게임 서버에 연결 중…",
    disconnected: "게임 서버 연결이 끊어졌습니다.", opponentDisconnected: "상대 연결이 끊어졌습니다.", serverUnavailable: "게임 서버를 사용할 수 없습니다. 온라인 PvP에는 WebSocket 서버가 필요합니다.",
    invalidServerResponse: "게임 서버가 올바르지 않은 응답을 보냈습니다.",
    roomWaiting: "{room}에서 상대를 기다리는 중…", sideSelectionReady: "{room} · 상대가 참가했습니다. 흑 또는 백을 선택하세요.", roomPlayer: "{room} · 나의 진영: {side}",
    serverRejected: "게임 서버가 요청을 거절했습니다.", enterRoomCode: "방 코드를 입력하세요.",
    resultWin: "{side} 승리", allEliminated: "상대 유닛이 모두 제거되었습니다.",
    timeExpired: "제한 시간(30초) 초과.",
    resultDraw: "무승부", draw: "무승부", boardFilled: "보드 종료: 흑 {red} - 백 {blue}.",
    noLegalMoves: "더 이상 둘 수 없어 종료: 흑 {red} - 백 {blue}.",
    autoPass: "{side}이(가) 턴을 넘겼습니다.", taunt: "쫄!", tauntBubble: "쫄!!",
    passNoticeTitle: "패스", noLegalMovesPass: "{side}은(는) 둘 곳이 없어 패스합니다.", confirm: "확인",
    suicideWarningTitle: "자살수 확인", suicideWarning: "이곳에 놓으면 이 유닛은 즉시 사망합니다.",
    cancelSuicide: "다시 선택", confirmSuicide: "그래도 두기",
    kingTerritoryBlocked: "상대가 5번째 배치를 완료하기 전까지 상대 왕 주변 8칸에는 배치할 수 없습니다.",
    kingOverlapBlocked: "상대 왕의 성역과 겹치는 위치(거리 3칸 미만)에는 왕을 배치할 수 없습니다.",
    kingCaptured: "{side} 왕이 포획되었습니다.",
    activateSpecialTitle: "{unit} 스킬 발동",
    activateSpecialPrompt: "{side}의 {unit}이(가) 포위되었습니다. 스킬을 발동해 포획 반응을 처리하세요.",
    activateSpecialButton: "{unit} 스킬 발동",
    waitingSpecialPrompt: "{side}의 포위된 특수 유닛 스킬 발동을 기다리는 중입니다.",
    puzzleComplete: "퍼즐 완료",
    puzzleFailed: "퍼즐 실패",
    puzzleSolvedReason: "정답입니다. {title} 퍼즐을 {moves}수 만에 해결했습니다.",
    tutorialPuzzleSolvedReason: "기본 수련을 완료했습니다. 다음 퍼즐로 이동하세요.",
    puzzleFailedReason: "제한 수에 도달했습니다. 다시 시도해보세요.",
    puzzleInvalidReason: "퍼즐 데이터가 올바르지 않습니다. 다른 퍼즐을 시도하세요.",
    puzzleProgress: "{rank} · 퍼즐 {current} / {total} · 남은 수 {movesLeft}",
  },
};

export function createUnitLabels(language) {
  return {
    soldier: TEXT[language].soldier,
    king: TEXT[language].king,
    general: TEXT[language].general,
    diplomat: TEXT[language].diplomat,
    wizard: TEXT[language].wizard,
  };
}

export function createSpecialHelp(language) {
  return {
    general: language === "ko"
      ? "장군의 집단이 완전히 포위되면 포획 판정 전에 인접한 적 유닛을 제거합니다."
      : "When its group is fully surrounded, the General removes adjacent enemy units before capture is resolved.",
    diplomat: language === "ko"
      ? "외교관의 집단이 완전히 포위되면 포획 판정 전에 인접한 적 유닛을 아군 병사로 전환합니다."
      : "When its group is fully surrounded, the Diplomat converts adjacent enemy units into friendly Soldiers before capture is resolved.",
    wizard: language === "ko"
      ? "마법사의 집단이 완전히 포위되면 인접한 적을 제거해 포위를 깨고 생존합니다. 이후 빈 칸으로 순간이동하거나 제자리에 남을 수 있습니다."
      : "When its group is fully surrounded, the Wizard removes adjacent enemies, breaks the surround, and survives. It may then teleport to an empty cell or stay in place.",
  };
}
