export const SIZE = 9;
export { PROTOCOL_VERSION } from "../packages/game-engine/src/constants.js";
export const WHITE_TERRITORY_BONUS = 0;
export const SPECIALS = new Set(["general", "diplomat", "wizard"]);
export const DEPLOY_ORDER = ["soldier", "general", "diplomat", "wizard", "king"];
export const AI_PROFILES = ["balanced", "aggressive", "defensive"];
export const PVE_HUMAN = "white";
export const PVE_AI = "black";

export const TEXT = {
  en: {
    appTitle: "Daeguk: Ascension", brandMain: "DAEGUK", brandSubtitle: "ASCENSION", splashEyebrow: "Daeguk", splashLoading: "Checking game server…", splashReady: "Entering lobby…", splashOffline: "Online server unavailable. Entering lobby…", splashImagePlaceholder: "Opening image",
    deploy: "Deploy", language: "Language", chooseMode: "Select Match", chooseModeDescription: "9×9 territory battle with Black playing 1st and White 2nd.",
    tutorial: "Tutorial", tutorialDescription: "Practice King placement, capture, fortress walls, and special abilities step by step.", puzzle: "Challenge", puzzleDescription: "Solve tactical puzzles to raise your rank.", challengeRanks: "Challenge Ranks", challengeRanksDescription: "Clear each rank to unlock the next challenge.", challengeComplete: "Challenge Complete", challengeIncomplete: "Challenge Incomplete", nextChallenge: "Next Challenge", retryChallenge: "Retry", backToChallenges: "Back to Challenges", rankLocked: "Locked", modeLocked: "Complete the tutorial to unlock", rankComplete: "Complete", rankReady: "Ready", comingSoon: "Coming Soon", exitTutorial: "Exit", nextTutorial: "Next",
    tutorialStep: "Step {current} / {total}", tutorialKing: "First, place your King.", tutorialKingPlaced: "Once the King is placed, a sanctuary appears around it. The King and the eight surrounding squares form the sanctuary.", tutorialSanctuaryDuration: "Your opponent cannot place a unit inside the sanctuary until you place four more units.",
    tutorialWallDefense: "A unit touching its own fortress wall gains one liberty from that wall. Place a Soldier on the highlighted square.",
    tutorialWallDefensePlaced: "The Black Soldier gained a liberty from its own fortress wall and was not captured.",
    tutorialWallCapture: "What happens when a unit touches the opponent's fortress wall? Place a Soldier on the highlighted square.",
    tutorialWallCapturePlaced: "The Black Soldier was blocked by White's fortress wall and was captured.",
    tutorialCapture: "A Soldier is captured when its group has no liberties left. Place a White Soldier on the highlighted square to capture the Black Soldier.",
    tutorialSpecialIntro: "Let's learn about special units. They become available after you place five units.",
    tutorialGeneral: "Special units activate their abilities when fully surrounded. Select the General and place it on the highlighted square.",
    tutorialDiplomat: "Select the Diplomat and place it on the highlighted square.",
    tutorialWizard: "Select the Wizard and place it on the highlighted square.",
    tutorialWizardTeleport: "The Wizard eliminated all adjacent enemies and can now teleport once. Teleport to the highlighted empty square.",
    wizardTeleportPrompt: "Select an empty square. If you do not want to move, select “Do Not Move”.",
    tutorialGeneralPlaced: "The General eliminated all adjacent enemies.",
    tutorialDiplomatPlaced: "The Diplomat converted all adjacent enemies to your side.",
    tutorialWizardPlaced: "Tutorial complete! You captured the Black King. You learned King placement, capture, fortress walls, and all three special abilities.",
    tutorialAiChallengePrompt: "Now challenge the Third-Rate Master in an AI match.",
    tutorialGeneralReady: "General placed. Press Next.",
    tutorialDiplomatReady: "Diplomat placed. Press Next.",
    tutorialWizardReady: "Wizard placed. Press Next.",
    tutorialGuideName: "Daeguk Lee",
    tutorialIntroDialogue: "Welcome to the world of Daeguk! I will guide you through the game.",
    tutorialIntroPage1: "Welcome to the world of Daeguk! I will guide you through the game.",
    tutorialIntroPage2: "Capture the enemy King for an instant win. Otherwise, the side with more territory wins when the match ends.",
    tutorialIntroPage4: "Black plays first, followed by White.",
    tutorialIntroPrompt: "Press Start to begin.",
    startTutorialAction: "Start",
    exitTutorialAction: "Exit",
    dialogueNext: "Next",
    dialoguePrev: "Back",
    tutorialBlackPreparing: "Black is placing the final surrounding Soldier…",
    tutorialSurroundComplete: "The unit is fully surrounded. Its special ability is activating…",
    tutorialCapturePlaced: "The Black Soldier was captured.",
    pveMode: "AI Match", pveDescription: "Play against the AI.", pveSidePrompt: "Choose a difficulty and timer, then decide who plays Black.", choosePreferredSide: "Play Rock-Paper-Scissors for Black (1st).",
    pveNovice: "Novice", pveIntermediate: "Intermediate", pveAdvanced: "Advanced", pveExpert: "Expert", pveGrandmaster: "Grandmaster",
    pveBeginner: "Novice",
    pveNoviceDescription: "Level 1: Basic tactical maneuvers and special units.",
    pveIntermediateDescription: "Level 2: Strategic positioning and diplomatic pressure.",
    pveAdvancedDescription: "Level 3: Teleportation tricks and unpredictable attacks.",
    pveExpertDescription: "Level 4: Multi-step foresight and coordinated trapping.",
    pveGrandmasterDescription: "Level 5: Fortified King play and precise finishing tactics.",
    pveBeginnerDescription: "Level 1: Basic tactical maneuvers and special units.",
    onlinePvp: "Online PvP", pvpDescription: "Create or join a private network room",
    networkLobby: "Network Lobby", networkPrompt: "Create a board or join an open board.", roomCode: "Room code",
    openRooms: "Open Boards", refreshRooms: "Refresh", noOpenRooms: "No open boards.", boardName: "Board {number}", boardWaiting: "Waiting",
    createBoard: "Create", enterBoard: "Enter",
    chooseSide: "Choose your side", chooseSideAfterJoin: "Both players joined. Choose Black (1st) or White (2nd).", blackSide: "Black (1st)", whiteSide: "White (2nd)", pveTimer: "Timer",
    enterCode: "Enter code", createRoom: "Create Room", joinRoom: "Join Room", back: "Back", lobby: "Lobby", requestRematch: "Request rematch", acceptRematch: "Accept Rematch", opponentRematchOffered: "Opponent requested a rematch.", rematchOfferedToast: "Opponent requested a rematch!", declineRematch: "Decline", opponentDeclinedRematch: "Opponent declined the rematch. Returned to lobby.", rematchDeclinedSelf: "Rematch declined. Returned to lobby.", opponentLeftRoom: "Opponent has left the room.",
    rpsPrompt: "The winner of Rock-Paper-Scissors plays Black (1st).", rpsWaitingOpponent: "Choice made! Waiting for opponent…", rpsDraw: "Draw! Choose again.", rpsWin: "You won! Starting as Black (1st).", rpsLose: "You lost! Starting as White (2nd).", scissors: "Scissors", rock: "Rock", paper: "Paper",
    dontShowAgain: "Do not show this unit explanation again", gotIt: "Got It", matchComplete: "Match Complete",
    blackTerritory: "Black territory", whiteTerritory: "White territory", blackCaptures: "Black captures", whiteCaptures: "White captures",
    playAgain: "Play Again", matchDetails: "Match Results", matchMetaPve: "AI Match", matchMetaNoviceRank: "Third-Rate Master", finishMethod: "Finish", totalDeployments: "Total deployments", deploymentTotalValue: "{count} moves", cancelAbility: "Do Not Move",
    undo: "Undo", resign: "Resign", resignConfirmTitle: "Do you want to resign?", cancel: "Cancel", confirm: "Confirm", resignReason: "{side} resigned.", home: "Home", newGame: "New Game", settings: "Settings", close: "Close", downloadPveJournal: "Download PvE record", pveJournalDownloaded: "PvE JSONL record downloaded.", soundSettings: "Sound", musicSetting: "Music", sfxSetting: "Effects", soundComingSoon: "Coming soon", blackUnits: "Black units", whiteUnits: "White units",
    soldier: "Soldier", king: "King", general: "General", diplomat: "Diplomat", wizard: "Wizard",
    used: "Used", kingFirst: "King first", left: "{count} left", available: "Available",
    black: "Black", white: "White", turn: "{side} turn", turnWithTime: "{side} turn {time}s", thinking: " thinking", wins: "{side} wins",
    hiddenUnit: "a hidden unit", notConnected: "The online match is not connected.", createOrJoin: "Create a board or enter an open board.",
    rematchWaiting: "Waiting for opponent…", connecting: "Connecting to game server…",
    disconnected: "Disconnected from game server.", opponentDisconnected: "Opponent disconnected.", serverUnavailable: "Game server is unavailable. Online PvP requires the WebSocket server.",
    invalidServerResponse: "The game server sent an invalid response.",
    roomWaiting: "{room}. Waiting for opponent…", sideSelectionReady: "{room} · Opponent joined. Choose Black or White.", roomPlayer: "{room} · You are {side}.",
    serverRejected: "The game server rejected the request.", enterRoomCode: "Enter a room code.",
    resultWin: "{side} Wins", allEliminated: "All enemy units were eliminated.",
    timeExpired: "Time limit exceeded (30s).",
    resultDraw: "Draw", draw: "Draw", boardFilled: "Board filled: Black {black} - White {white}.",
    noLegalMoves: "No legal deployments remained: Black {black} - White {white}.",
    autoPass: "{side} passed the turn.", taunt: "Taunt", tauntBubble: "Coward", generalTauntBubble: "How dare you block me!", diplomatTauntBubble: "Name your price", wizardTauntBubble: "Abracadabra",
    passNoticeTitle: "Pass", noLegalMovesPass: "{side} has no legal moves and passes the turn.", confirm: "OK",
    suicideWarningTitle: "Confirm Suicide Move", suicideWarning: "This unit will die immediately if placed here.",
    enclosedSpecialTitle: "Ability Fires Immediately", enclosedSpecialWarning: "This point is fully enclosed, so the ability activates the moment you place.",
    cancelSuicide: "Reselect", confirmSuicide: "Place Anyway",
    kingTerritoryBlocked: "You cannot deploy inside the opponent King's surrounding territory until that player completes five deployments.",
    kingOverlapBlocked: "The King's sanctuary cannot overlap with the opponent King's sanctuary (must be at least 3 squares apart).",
    kingCaptured: "{side} King was captured.",
    puzzleComplete: "Puzzle Complete",
    puzzleFailed: "Puzzle Failed",
    puzzleSolvedReason: "Correct. {title} solved in {moves} move(s).",
    tutorialPuzzleSolvedReason: "Basic training complete. Continue to the next puzzle.",
    puzzleFailedReason: "The move limit was reached. Try the puzzle again.",
    puzzleInvalidReason: "This puzzle data is invalid. Please try another puzzle.",
    puzzleProgress: "{rank} · Puzzle {current} / {total} · {movesLeft} move(s) left",
  },
  ko: {
    appTitle: "고수의 대국", brandMain: "DAEGUK", brandSubtitle: "고수의 대국", splashEyebrow: "대국", splashLoading: "게임 서버 확인 중…", splashReady: "로비로 이동 중…", splashOffline: "온라인 서버를 사용할 수 없습니다. 로비로 이동 중…", splashImagePlaceholder: "대문 이미지",
    deploy: "유닛 배치", language: "언어", chooseMode: "대국 선택", chooseModeDescription: "흑돌 선공, 백돌 후공으로 진행되는 9×9 대국",
    tutorial: "튜토리얼", tutorialDescription: "왕 배치, 포획, 성벽과 특수 능력을 단계별로 연습하세요.", puzzle: "챌린지", puzzleDescription: "퍼즐을 풀어 자신의 등급을 올리세요.", challengeRanks: "챌린지", challengeRanksDescription: "각 등급을 완료하면 다음 챌린지가 열립니다.", challengeComplete: "챌린지 완료", challengeIncomplete: "챌린지 미완료", nextChallenge: "다음 챌린지", retryChallenge: "다시 도전", backToChallenges: "챌린지로", rankLocked: "잠김", modeLocked: "튜토리얼 완료 후 해금", rankComplete: "완료", rankReady: "도전 가능", comingSoon: "준비 중", exitTutorial: "종료", nextTutorial: "다음",
    tutorialStep: "{current} / {total} 단계", tutorialKing: "먼저 왕을 배치하세요.", tutorialKingPlaced: "왕이 배치되면 왕을 둘러싼 성역이 나타납니다. 왕과 주변 8칸이 성역입니다.", tutorialSanctuaryDuration: "자신의 돌을 네 개 더 놓을 때까지 상대는 성역 안에 배치할 수 없습니다.",
    tutorialWallDefense: "자기 성벽에 닿은 돌은 성벽 쪽에 활로 하나를 얻습니다. 표시된 칸에 병사를 놓아보세요.",
    tutorialWallDefensePlaced: "흑 병사는 흑의 성벽에서 활로를 얻어 포획되지 않았습니다.",
    tutorialWallCapture: "상대 성벽에 닿은 돌은 어떻게 될까요? 표시된 칸에 병사를 놓아보세요.",
    tutorialWallCapturePlaced: "흑 병사는 백의 성벽에 막혀 포획되었습니다.",
    tutorialCapture: "돌은 상하좌우의 활로가 모두 막히면 포획됩니다. 표시된 칸에 백 병사를 놓아 흑 병사를 잡으세요.",
    tutorialSpecialIntro: "특수 유닛을 배워 봅시다. 대국 시작 후 자신의 돌을 다섯 번 놓은 후부터 특수 유닛을 사용할 수 있습니다.",
    tutorialGeneral: "특수 유닛은 완전히 포위될 때 능력을 발동합니다. 장군 돌을 선택하고 표시된 칸에 장군을 놓아보세요.",
    tutorialDiplomat: "외교관 돌을 선택하고 표시된 칸에 외교관을 놓아보세요.",
    tutorialWizard: "마법사 돌을 선택하고 표시된 칸에 마법사를 놓아보세요.",
    tutorialWizardTeleport: "마법사가 인접한 적을 모두 제거하였습니다. 마법사는 능력이 발동한 후 즉시 한 번 순간이동할 수 있습니다. 표시된 빈칸으로 이동하세요.",
    wizardTeleportPrompt: "빈칸을 선택하세요. 이동을 원하지 않으면 ‘이동 안 함’을 선택하세요.",
    tutorialGeneralPlaced: "장군이 인접한 적을 모두 제거하였습니다.",
    tutorialDiplomatPlaced: "외교관이 인접한 적을 모두 아군으로 바꾸었습니다.",
    tutorialWizardPlaced: "튜토리얼 완료! 흑 왕을 포획하여 승리했습니다. 왕 배치, 포획, 성벽과 세 특수 유닛의 능력을 익혔습니다.",
    tutorialAiChallengePrompt: "이제 AI 대전에서 삼류 고수에 도전해 보세요.",
    tutorialGeneralReady: "장군을 배치했습니다. 다음을 누르세요.",
    tutorialDiplomatReady: "외교관을 배치했습니다. 다음을 누르세요.",
    tutorialWizardReady: "마법사를 배치했습니다. 다음을 누르세요.",
    tutorialGuideName: "이대국",
    tutorialIntroDialogue: "대국의 세계에 오신 것을 환영합니다! 대국 게임을 안내해 드리겠습니다.",
    tutorialIntroPage1: "대국의 세계에 오신 것을 환영합니다! 대국 게임을 안내해 드리겠습니다.",
    tutorialIntroPage2: "이 대국은 상대 왕을 잡으면 즉시 승리합니다. 왕을 잡지 못한 채 승부가 끝나면 더 많은 영토를 가진 쪽이 승리합니다.",
    tutorialIntroPage4: "흑돌이 선공하고 백돌이 후공하여 대국을 시작합니다.",
    tutorialIntroPrompt: "시작하기를 누르세요.",
    startTutorialAction: "시작하기",
    exitTutorialAction: "나가기",
    dialogueNext: "다음",
    dialoguePrev: "이전",
    tutorialBlackPreparing: "흑이 마지막 포위 병사를 놓고 있습니다…",
    tutorialSurroundComplete: "특수 유닛이 완전히 포위되었습니다. 능력을 발동합니다…",
    tutorialCapturePlaced: "흑 병사가 포획되었습니다.",
    pveMode: "AI 대국", pveDescription: "AI와 대국하세요.", pveSidePrompt: "난이도와 타이머를 선택한 뒤 흑을 정하세요.", choosePreferredSide: "가위바위보로 흑(선공)을 정하세요.",
    pveNovice: "삼류 고수", pveIntermediate: "이류 고수", pveAdvanced: "일류 고수", pveExpert: "절정 고수", pveGrandmaster: "초절정 고수",
    pveBeginner: "삼류 고수",
    pveNoviceDescription: "1단계: 특수 기물 기본 활용 및 전술 공방",
    pveIntermediateDescription: "2단계: 외교관 및 진형 장악 중심 전략",
    pveAdvancedDescription: "3단계: 마법사 도약 및 기습 침투 전술",
    pveExpertDescription: "4단계: 2~3수를 내다보는 연계 수읽기",
    pveGrandmasterDescription: "5단계: 견고한 왕 방어와 정밀한 마무리 전술",
    pveBeginnerDescription: "1단계: 특수 기물 기본 활용 및 전술 공방",
    onlinePvp: "온라인 대국", pvpDescription: "비공개 방을 만들거나 참가",
    networkLobby: "온라인 대기실", networkPrompt: "대국장을 만들거나 열린 대국장에 참가하세요.", roomCode: "방 코드",
    openRooms: "열린 대국장", refreshRooms: "새로고침", noOpenRooms: "열린 대국장이 없습니다.", boardName: "제{number}대국장", boardWaiting: "대기 중",
    createBoard: "만들기", enterBoard: "입장",
    chooseSide: "진영 선택", chooseSideAfterJoin: "두 플레이어가 참가했습니다. 흑(선공) 또는 백(후공)을 선택하세요.", blackSide: "흑 (선공)", whiteSide: "백 (후공)", pveTimer: "타이머",
    enterCode: "코드 입력", createRoom: "방 만들기", joinRoom: "방 참가", back: "뒤로", lobby: "로비", requestRematch: "재대국 요청", acceptRematch: "재대국 수락", opponentRematchOffered: "상대가 재대국을 요청했습니다.", rematchOfferedToast: "상대방이 재대국을 신청했습니다!", declineRematch: "거절", opponentDeclinedRematch: "상대방이 재대국을 거절하여 온라인 대기실로 이동했습니다.", rematchDeclinedSelf: "재대국을 거절하고 온라인 대기실로 이동했습니다.", opponentLeftRoom: "상대방이 대국실을 나갔습니다.",
    rpsPrompt: "가위바위보를 이기는 사람이 흑(선공)을 잡습니다.", rpsWaitingOpponent: "선택 완료! 상대의 선택을 기다리는 중…", rpsDraw: "비겼습니다! 다시 선택하세요.", rpsWin: "가위바위보 승리! 흑(선공)으로 시작합니다.", rpsLose: "가위바위보 패배! 백(후공)으로 시작합니다.", scissors: "가위", rock: "바위", paper: "보",
    dontShowAgain: "이 유닛 설명을 다시 표시하지 않기", gotIt: "확인", matchComplete: "대국 종료",
    blackTerritory: "흑 영역", whiteTerritory: "백 영역", blackCaptures: "흑 포획", whiteCaptures: "백 포획",
    playAgain: "다시 대국", matchDetails: "경기 결과", matchMetaPve: "AI 대전", matchMetaNoviceRank: "삼류 고수", finishMethod: "종료 방식", totalDeployments: "총 배치 수", deploymentTotalValue: "{count}수", cancelAbility: "이동 안 함",
    undo: "한 수 물리기", resign: "기권", resignConfirmTitle: "기권하시겠습니까?", cancel: "취소", confirm: "확인", resignReason: "{side} 기권패", home: "홈", newGame: "새 게임", settings: "설정", close: "닫기", downloadPveJournal: "PvE 대국 기록 내려받기", pveJournalDownloaded: "PvE JSONL 대국 기록을 내려받았습니다.", soundSettings: "사운드", musicSetting: "배경음악", sfxSetting: "효과음", soundComingSoon: "준비 중", blackUnits: "흑 유닛", whiteUnits: "백 유닛",
    soldier: "병사", king: "왕", general: "장군", diplomat: "외교관", wizard: "마법사",
    used: "사용 완료", kingFirst: "왕 먼저", left: "{count}개", available: "사용 가능",
    black: "흑", white: "백", turn: "{side} 턴", turnWithTime: "{side} 턴 {time}s", thinking: " 생각 중", wins: "{side} 승리",
    hiddenUnit: "숨겨진 유닛", notConnected: "온라인 경기에 연결되지 않았습니다.", createOrJoin: "대국장을 만들거나 입장하세요.",
    rematchWaiting: "재대국 요청됨 (대기 중…)", connecting: "게임 서버에 연결 중…",
    disconnected: "게임 서버 연결이 끊어졌습니다.", opponentDisconnected: "상대 연결이 끊어졌습니다.", serverUnavailable: "게임 서버를 사용할 수 없습니다. 온라인 PvP에는 WebSocket 서버가 필요합니다.",
    invalidServerResponse: "게임 서버가 올바르지 않은 응답을 보냈습니다.",
    roomWaiting: "{room}에서 상대를 기다리는 중…", sideSelectionReady: "{room} · 상대가 참가했습니다. 흑 또는 백을 선택하세요.", roomPlayer: "{room} · 나의 진영: {side}",
    serverRejected: "게임 서버가 요청을 거절했습니다.", enterRoomCode: "방 코드를 입력하세요.",
    resultWin: "{side} 승리", allEliminated: "상대 유닛이 모두 제거되었습니다.",
    timeExpired: "제한 시간(30초) 초과.",
    resultDraw: "무승부", draw: "무승부", boardFilled: "보드 종료: 흑 {black} - 백 {white}.",
    noLegalMoves: "더 이상 둘 수 없어 종료: 흑 {black} - 백 {white}.",
    autoPass: "{side}이(가) 턴을 넘겼습니다.", taunt: "쫄", tauntBubble: "쫄", generalTauntBubble: "감히 나를 막아", diplomatTauntBubble: "얼마면 돼", wizardTauntBubble: "아브라카다브라",
    passNoticeTitle: "패스", noLegalMovesPass: "{side}은(는) 둘 곳이 없어 패스합니다.", confirm: "확인",
    suicideWarningTitle: "자살수 확인", suicideWarning: "이곳에 놓으면 이 유닛은 즉시 사망합니다.",
    enclosedSpecialTitle: "능력 즉시 발동", enclosedSpecialWarning: "사방이 막힌 자리라 놓는 즉시 능력이 발동합니다.",
    cancelSuicide: "다시 선택", confirmSuicide: "그래도 두기",
    kingTerritoryBlocked: "상대가 5번째 배치를 완료하기 전까지 상대 왕 주변 8칸에는 배치할 수 없습니다.",
    kingOverlapBlocked: "상대 왕의 성역과 겹치는 위치(거리 3칸 미만)에는 왕을 배치할 수 없습니다.",
    kingCaptured: "{side} 왕이 포획되었습니다.",
    puzzleComplete: "퍼즐 완료",
    puzzleFailed: "퍼즐 실패",
    puzzleSolvedReason: "정답입니다. {title} 퍼즐을 {moves}수 만에 해결했습니다.",
    tutorialPuzzleSolvedReason: "기본 수련을 완료했습니다. 다음 퍼즐로 이동하세요.",
    puzzleFailedReason: "제한 수에 도달했습니다. 다시 시도해보세요.",
    puzzleInvalidReason: "퍼즐 데이터가 올바르지 않습니다. 다른 퍼즐을 시도하세요.",
    puzzleProgress: "{rank} · 퍼즐 {current} / {total} · 남은 수 {movesLeft}",
  },
};

export function createUnitLabels(language) {
  return {
    soldier: TEXT[language].soldier,
    king: TEXT[language].king,
    general: TEXT[language].general,
    diplomat: TEXT[language].diplomat,
    wizard: TEXT[language].wizard,
  };
}

export function createSpecialHelp(language) {
  return {
    general: language === "ko"
      ? "장군의 집단이 완전히 포위되면 포획 판정 전에 인접한 적 유닛을 제거합니다."
      : "When its group is fully surrounded, the General removes adjacent enemy units before capture is resolved.",
    diplomat: language === "ko"
      ? "외교관의 집단이 완전히 포위되면 포획 판정 전에 인접한 적 유닛을 아군 병사로 전환합니다."
      : "When its group is fully surrounded, the Diplomat converts adjacent enemy units into friendly Soldiers before capture is resolved.",
    wizard: language === "ko"
      ? "마법사의 집단이 완전히 포위되면 인접한 적을 제거해 포위를 깨고 생존합니다. 이후 빈 칸으로 순간이동하거나 제자리에 남을 수 있습니다."
      : "When its group is fully surrounded, the Wizard removes adjacent enemies, breaks the surround, and survives. It may then teleport to an empty cell or stay in place.",
  };
}
